config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'

  resources :chapters, only: [:index, :show]

  get 'curriculum', to: redirect('materials')

  resources :materials, only: [:index, :show]
  get '/materials/:slug' => 'materials#show', as: :course

  get 'get-involved', to: 'home#get-involved'
  get 'code-of-conduct', to: 'home#code-of-conduct'
  get 'codeofconduct', to: redirect('code-of-conduct')

  resources :meetups, param: :slug, only: [:show]

  scope module: 'home' do
    get 'about'
    get 'faq'
    get 'jobs'
    get 'supporters'
    get 'sponsors', to: redirect('supporters')

    get 'donate'
    get 'summit'
    
  end

  get '*any', via: :all, to: 'errors#not_found'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    allroles = []
    user.roles.each do |r|
      allroles << r.name
    end
    if allroles.include? "admin"
      can :manage, :all
    elsif allroles.include? "leader"
      #allow view of Dashboard page
      can :read, ActiveAdmin::Page, name: 'Dashboard'

      #leader can only view/update chapter details (not create)
      can [:read, :view, :manage], Chapter, :id => user.chapter_id
     
      #only list/manage the bios and sponsors related leader's chapter
      can [:manage, :read, :view], [Bio, Sponsor], :chapter_id => user.chapter_id

      #leader can create new bios and sponsors, but chapter_id is hidden in form
      can :create, [Bio, Sponsor]

      #leaders cannot create new chapters
      cannot :create, Chapter

      #leaders cannot view adminuser page
      cannot :read, AdminUser
    else
      can :view, :all
    end

    #check if user's chapter is active
    #if not, only let them see Dashboard with information about deactivation
    @user_chapter = Chapter.where(id: user.chapter_id)
    @user_chapter.each do |c|
      if !c.is_active
        cannot :read, :all
        can :read, ActiveAdmin::Page, name: 'Dashboard'
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :bio
  belongs_to :chapter
  accepts_nested_attributes_for :roles

	def admin?
    roles.any?{|role| role.name == "admin"}
	end
  
end

app/models/bio.rb
class Bio < ActiveRecord::Base
  resourcify
  belongs_to :admin_user
  belongs_to :chapter

  mount_uploader :image, ProfileImageUploader
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  extend FriendlyId
  friendly_id :chapter, use: [:slugged, :history]

  validates :geo, :chapter, presence: true

  resourcify
  has_many :admin_users
  has_many :sponsors
  has_many :bios

  geocoded_by :geo
  after_validation :geocode
  after_validation :geocode, :if => :geo_changed?

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geocoded = results.first
      obj.state = geocoded.state
    end
  end

  #check that state field is set
  def is_state_null
    if self.state?
      return true
    else
      #otherwise, throw error under "address" field in AA
      errors.add(:geo, "Please enter a valid location (example: \"Los Angeles, CA, USA\")")
      return false
    end
  end

  #make sure we have a state after geocode process
  before_save :is_state_null

  after_validation :reverse_geocode
  
  scope :active, -> { where(is_active: true) }
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  extend FriendlyId
  friendly_id :location, use: [:slugged, :history]

  resourcify
  has_many :admin_users
  has_many :sponsors
  has_many :bios

  geocoded_by :geo
  after_validation :geocode
  after_validation :geocode, :if => :geo_changed?

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geocoded = results.first
      obj.state = geocoded.state
    end
  end
  after_validation :reverse_geocode
end

app/models/material.rb
class Material < ActiveRecord::Base
  resourcify
  mount_uploader :icon, MaterialIconUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  resourcify
  has_and_belongs_to_many :admin_users, :join_table => :admin_users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  resourcify
  belongs_to :chapter
  mount_uploader :image, SponsorImageUploader

  scope :active, -> { where(is_active: true) }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def access_denied(exception)
    redirect_to root_path, :alert => exception.message
  end


  # private
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   # binding.pry
  #   root_path
  # end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  require 'rails_autolink'
  def index
    @chapters = Chapter.active.order("chapter ASC")
    states = {}
    @chapters.each do |l|
      if states[l.state]
        states[l.state] << l.chapter
      else
        states[l.state] = [l.chapter]
      end
    end
    @states = states.to_a.sort

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @chapters }
  end
end

  def show
    @chapter = Chapter.friendly.find(params[:id])
    #Make sure the chapter is active otherwise redirect to index
    if !@chapter.is_active
      redirect_to({ action: 'index' }, alert: @chapter.chapter + " is no longer an active chapter.")
    end
    if request.path != chapter_path(@chapter)
      redirect_to @chapter, status: :moved_permanently
    end
    @users = @chapter.admin_users
    @sponsors = @chapter.sponsors.active.order("sort_order ASC")

    @bios = @chapter.bios
    @leaders = @bios.where(title: "LEADERS").order("sort_order ASC")
    @organizers = @bios.where(title: "ORGANIZERS").order("sort_order ASC")
    @instructors = @bios.where(title: "INSTRUCTORS").order("sort_order ASC")
    @volunteers = @bios.where(title: "VOLUNTEERS").order("sort_order ASC")

    api = MeetupApi.new
    @events = api.events(group_id: @chapter.meetup_id)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  @chapters = Chapter.active
  @chapter = Chapter.active
  end

  def about
  	@chapter_count = Chapter.active.count
  end

  def donate
    @chapter_count = Chapter.active.count
  end

  def supporters
  	@chapter_count = Chapter.active.count
  end

  def summit
    @chapter_count = Chapter.active.count
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  require 'rails_autolink'
  def index
    @materials = Material.order("sort_order ASC").all

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @materials }
  end
end

  def show
   @material = Material.find_by(slug: params[:id])
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController

  def show
    ## Someday there will be caching here!
    @chapter = Chapter.find_by(slug: params[:slug])

    params = { group_id: @chapter.meetup_id, key: ENV["MEETUP_API_KEY"]}
    meetup_api = MeetupApi.new
    @glob = meetup_api.events(params)
    @results = @glob["results"]

    respond_to do |format|
      format.json { render json: @results }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_page(path)
    "active-nav" if current_page?(path)
  end

  def full_title(page_title = '')
    base_title = "Girl Develop It"
    if page_title.empty?
      base_title
    else
      "#{page_title}  -  #{base_title}"
    end
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
  def image_route(s)
    "state_map/#{s.parameterize}.png"
  end

  def linkedin_link(chapter_linkedin)
    chapter_linkedin.downcase!
    if chapter_linkedin.match("^https?:\/\/www\.linkedin\.com")
        return chapter_linkedin
    else
        return "https://www.linkedin.com/#{chapter_linkedin}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  def image_route(s)
    "state_map/#{s.parameterize}.png"
  end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/chapters/index.html.erb
<% provide(:title, "Chapters") %>
  <section class="main-container">
    <div class="container">

      <div class="underlined-headline">
        <h2>We are now in <%= @chapters.count %> cities!</h2>
          <hr>
          <p class="subtitle hide">Don't see your hometown?
            <% if current_admin_user != nil %>
              <%= link_to "Start a new chapter!", "#{root_path}admin/chapters/new" %>
              <% else %>
              <a href="https://docs.google.com/forms/d/18vn6QF64wg8i7euJXSA4HlYWO4AlL9i04o7057-ewuQ/viewform" target="_blank" >Start a new chapter!</a>
            <% end %>
          </p>
      </div>

      <section class="state-index hide">
        <% @states.each do |s| %>
          <div class="state-container">
            <div class="state"><%= image_tag(image_route(s[0])) %></div>
            <hr>
            <h2><%= s[0] %></h2>
            <% s[1].each do |l| %>
              <h3 class="large"><%= link_to l, chapter_path(l.parameterize) %></h3>
            <% end %>
          </div>
        <% end %>
      </section>

      <section id="state-list">
        <div class="collapsible show">
          <% @states.each do |s| %>
            <h3><span class="chevron-closed">&nbsp;</span>
               <%= s[0] %>
            </h3>
            <div>
              <% s[1].each do |l| %>
                <p><%= link_to l, chapter_path(l.parameterize) %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </section>
    </div>
  </section>

app/views/chapters/show.html.erb
<% provide(:title, "#{@chapter.chapter}") %>
<section class="main-container">
  <div class="container">
    <aside class="chapter-aside">
      <div class="state-container-aside">
        <%= link_to image_tag(image_route(@chapter.state)), chapters_path %>
      </div>
      <hr>
      <h1><%= @chapter.chapter %></h1>

      <%= render partial: "social_media_chapter", locals: {chapter: @chapter} %>

      <p class="subtitle">- don't be shy -</p>
      <%= link_to "{ Join Us }", "http://www.meetup.com/#{@chapter.meetup}", :class=>"button" %>

      <% if @chapter.sponsors.count != 0 %>
          <div class="supporters">
            <h2>Sponsors</h2>
            <div class="logos">
              <% @sponsors.each do |sponsor| %>
                <% if sponsor.image? %>
                  <%= link_to image_tag(sponsor.image.url, alt: sponsor.name, title: sponsor.name), sponsor.url, target: "_blank" %>
                <% elsif sponsor.name? %>
                  <%= link_to sponsor.url, target: "_blank", :class=>"subtitle" do %>
                    { <%= sponsor.name %> }
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <p>
              Interested in becoming a sponsor?
              <%= mail_to @chapter.email, "Contact the chapter", subject: "Sponsoring the #{@chapter.chapter} Chapter" %>
            </p>
          </div>
      <% end %>
    </aside>

    <section id="content-section">
      <div class="headline">
        <%= image_tag 'pencil.png' %>
        <h2>Upcoming Events</h2>
      </div>

      <div class="classes">
      </div>

      <% if @leaders.count != 0 %>
       <%= render partial: "profiles_sections", locals: {title: 'The Leaders', bios: @leaders} %>
      <% end %>

      <% if @organizers.count != 0 %>
        <%= render partial: "profiles_sections", locals: {title: 'The Organizers', bios: @organizers} %>
      <% end %>

      <% if @instructors.count != 0 %>
        <%= render partial: "profiles_sections", locals: {title: 'The Instructors', bios: @instructors} %>
      <% end %>

      <% if @volunteers.count != 0 %>
        <%= render partial: "profiles_sections", locals: {title: 'The Volunteers', bios: @volunteers} %>
      <% end %>


      <script type="text/template" id="meetup">
        <%% _.each( classesArr,function(course){ %>
          <div class="meetup-overview">
            <h3>
              <a href="<%%= course.event_url %>"><%%= course.name %></a>
              <%% if( typeof course.rsvp_limit !== "undefined " && course.yes_rsvp_count >= course.rsvp_limit) { %><span class="closed">sold out</span>
              <%% } %>
            </h3>
            <p class="subtitle">[ <%%= moment(course.time).format("dddd, MMMM Do YYYY, h:mm a") %>
            <%% if(typeof course.venue !== "undefined" ) { %>
                , <a href=" https://maps.google.com/?q=<%%= course.venue.address_1 %>, <%%= course.venue.city %>, <%%= course.venue.state %>"><%%= course.venue.address_1 %>, <%%= course.venue.city %>, <%%= course.venue.state %></a>
              <%% } %>
              ] </p>
              <%# MOVING MAP PARTIAL BELOW PARAGRAPH UNTIL GOOGLE API KEY IS AVAILABLE %>
              <%#= render partial: "meetup_map"%>
             <p><%%= course.description.substring(0, 400) %><a href="<%%= course.event_url %>"> &hellip;read more</a></p>
             <%% if( typeof course.venue !== "undefined" ||  course.rsvp_limit !== "undefined " && course.yes_rsvp_count >= course.rsvp_limit) { } else { %>
                <p><a href="<%%= course.event_url %>" class="button">RSVP</a></p>
              <%% } %>
              <%= render partial: "meetup_map"%>
          </div>
        <%% }); %>
      </script>

      <script type="text/javascript">

        var meetup_url = '/meetups/<%= params[:id] %>.json';
        var classesArr = null;
        $.getJSON(meetup_url).done(function (classesData){
          if(classesData.length>0) {
            classesArr = classesData.slice(0,3);
            var classes = $('#meetup').html();
            //instead send classesArr to template where _.each is waiting...
            //idea seen here: http://stackoverflow.com/questions/4778881/how-to-use-underscore-js-as-a-template-engine
            $(".classes").html(_.template(classes,classesArr));
            $(".classes").append("<p><a href=\"http://meetup.com/<%= @chapter.meetup %>\">More Events</a></p>");
          } else {
            $(".classes").html("<p class=\"uhOh\">Sadly, no meetups are currently scheduled for this Chapter. <a href=\"http://meetup.com/<%= @chapter.meetup %>\">Join our meetup group</a> to be notified when a new meetup is happening. Thanks for visiting us!</p>")};
          });

      </script>
    </section>
  </div>
</section>

app/views/home/event.html.erb
<div class="opener">
    <%#= image_tag("photo2.png") %>
    <h1><span class="animated fadeInLeft">Don't be shy</span> <%= image_tag("flourish-med.png" , class: "hide") %> <span class="animated fadeInRight">Develop it</span></h1>
  </div>

  <div class="container" >
  	<section class="mission-statement">
      <div class="underlined-headline">
        <h2>Who We Are</h2>
        <hr>
      </div>
    	<p class="large">Girl Develop It is a nonprofit organization that exists to provide affordable and judgment-free opportunities for women interested in learning web and software development. Through in-person classes and community support, Girl Develop It helps women of diverse backgrounds achieve their technology goals and build confidence in their careers and their every day lives.</p>
      <%= link_to "[ Learn more ]", about_path, :class=>"subtitle"%>
    </section>
  </div>

  <section class="map">
    <div class="container">
    	<div class="underlined-headline">
        <h2>Join Our Classes!</h2>
        <hr>
           
        <p class="subtitle hide">
          Don't see your hometown?
          <% if current_admin_user != nil %>
            <%= link_to "Start a new chapter!", "#{root_path}admin/chapters/new" %>
            <% else %>
            <a href="https://docs.google.com/a/girldevelopit.com/forms/d/18vn6QF64wg8i7euJXSA4HlYWO4AlL9i04o7057-ewuQ/viewform">Start a new chapter!</a>
          <% end %>
        </p>
        <%=link_to "Find GDI in your hometown!", chapters_path, :class=>" subtitle show-inline"%>
      </div>
      <div class="us_map hide">
        <div class="map"></div>
      </div>
    </div>
  </section>

  <section class="stats-section">
    <div class="container">
      <div class="stats">
        <%= image_tag("homepage-stat1.png", :alt => "26 percent") %>
        <p>Women hold only 26% of the approximately four million computing related occupations in the US. <%= link_to "U.S. Department of Labor, Bureau of Labor Statistics, 2013 (Occupational Category: 15–0000)", "http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf", target: "_blank" %></p>
      </div>
      <div class="stats">
        <%= image_tag("homepage-stat2.png", :alt => "18 percent") %>
        <p>Women obtain 57% of bachelor’s degrees in the U.S, but fewer than 18% of those degrees are in computer science. (Compared to 1984, when women earned 37%) <%= link_to "National Center for Education Statistics (NCES), 2012 (CIP 11)", "http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf", target: "_blank" %></p>
      </div>
      <div class="stats">
        <%= image_tag("homepage-stat3.png", :alt => "34 percent") %>
        <p>Tech companies with more women in management have a 34% higher return of investment. <%= link_to "National Center for Women and IT Fact Sheet", "http://www.ncwit.org/sites/default/files/resources/ncwitfactsheet.pdf", target: "_blank" %></p>
      </div>
    </div>
  </section>

  <div class="press-logos">
    <h3>{ As seen in }</h3>
    <%#= image_tag("press-logos.png") %>
    <%= link_to image_tag("as_seen_in/code_org.png"), "https://www.youtube.com/watch?v=nKIu9yen5nc", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/tnyt.png"), "http://www.nytimes.com/2012/03/28/technology/for-an-edge-on-the-internet-computer-code-gains-a-following.html", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/ted.png"), "http://blog.ted.com/2013/01/29/10-places-where-anyone-can-learn-to-code/", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/fast_company.png"), "http://www.fastcompany.com/1776382/female-geeks-flex-their-skills-ladies-only-hackathon", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/lifehacker.png"), "http://lifehacker.com/5872682/learn-to-code-in-2012-with-free-weekly-programming-lessons-from-codecademy", target: "_blank" %>
  </div>
  <script>
    var chapter_id = "chapters/3";
  </script>

app/views/home/index.html.erb
  <div class="opener">
    <%#= image_tag("photo2.png") %>
    <h1><span class="animated fadeInLeft">Don't be shy</span> <%= image_tag("flourish-med.png" , class: "hide") %> <span class="animated fadeInRight">Develop it</span></h1>
  </div>

  <div class="container" >
  	<section class="mission-statement">
      <div class="underlined-headline">
        <h2>Welcome to Girl Develop It</h2>
        <hr>
      </div>
    	<p class="large">We are a nonprofit organization that provides affordable programs for adult women and non-binary individuals to learn web and software development in a judgement free environment.</p>
      <%= link_to "[ Learn more ]", about_path, :class=>"subtitle"%>
    </section>
  </div>

  <section class="map">
    <div class="container">
    	<div class="underlined-headline">
        <h2>Take a Class</h2>
        <hr>
        <div id="eventbrite-widget-container-101539555544" class="profile profile-left"></div>

<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };

    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '101539555544',
        iframeContainerId: 'eventbrite-widget-container-101539555544',

        // Optional
        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>
      
      <div id="eventbrite-widget-container-102114930506" class="profile profile-right"></div>

<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };

    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '102114930506',
        iframeContainerId: 'eventbrite-widget-container-102114930506',

        // Optional
        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>
   
      </div>
    </div>
  </section>

  <section class="stats-section">
    <div class="container">
      <div class="stats">
        <%= image_tag("homepage-stat1.png", :alt => "26 percent") %>
        <p>Women hold only 26% of the approximately four million computing related occupations in the US. <%= link_to "U.S. Department of Labor, Bureau of Labor Statistics, 2013 (Occupational Category: 15–0000)", "http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf", target: "_blank" %></p>
      </div>
      <div class="stats">
        <%= image_tag("homepage-stat2.png", :alt => "18 percent") %>
        <p>Women obtain 57% of bachelor’s degrees in the U.S, but fewer than 18% of those degrees are in computer science. (Compared to 1984, when women earned 37%) <%= link_to "National Center for Education Statistics (NCES), 2012 (CIP 11)", "http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf", target: "_blank" %></p>
      </div>
      <div class="stats">
        <%= image_tag("homepage-stat3.png", :alt => "34 percent") %>
        <p>Tech companies with more women in management have a 34% higher return of investment. <%= link_to "National Center for Women and IT Fact Sheet", "http://www.ncwit.org/sites/default/files/resources/ncwitfactsheet.pdf", target: "_blank" %></p>
      </div>
    </div>
  </section>

  <div class="press-logos">
    <h3>{ As seen in }</h3>
    <%#= image_tag("press-logos.png") %>
    <%= link_to image_tag("as_seen_in/code_org.png"), "https://www.youtube.com/watch?v=nKIu9yen5nc", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/tnyt.png"), "http://www.nytimes.com/2012/03/28/technology/for-an-edge-on-the-internet-computer-code-gains-a-following.html", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/ted.png"), "http://blog.ted.com/2013/01/29/10-places-where-anyone-can-learn-to-code/", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/fast_company.png"), "http://www.fastcompany.com/1776382/female-geeks-flex-their-skills-ladies-only-hackathon", target: "_blank" %>
    <%= link_to image_tag("as_seen_in/lifehacker.png"), "http://lifehacker.com/5872682/learn-to-code-in-2012-with-free-weekly-programming-lessons-from-codecademy", target: "_blank" %>
  </div>
  <script>
    var chapter_id = "chapters/3";
  </script>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="footer">
			<p class="subtitle hide">Don't see your city? <a target="_blank" href="https://docs.google.com/forms/d/18vn6QF64wg8i7euJXSA4HlYWO4AlL9i04o7057-ewuQ/viewform">Help bring Girl Develop It to your community!</a></p>
			<p class="subtitle">To learn about ways to support Girl Develop It, email us at <%= mail_to "sponsorships@girldevelopit.com" %> or visit our <%= link_to "Donate", donate_path %> page.</p>
			<!-- Begin MailChimp Signup Form -->

			<div id="mc_embed_signup">
			<form action="//girldevelopit.us2.list-manage.com/subscribe/post?u=4d5ae11ec6fb973947670055f&amp;id=e63c9ab02b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
			    <div id="mc_embed_signup_scroll">
				<!-- <label for="mce-EMAIL">Subscribe to our mailing list</label><br> -->
				<input type="email" value="" name="EMAIL" title="Email address" class="email" id="mce-EMAIL" size="40" placeholder="email address" required>
			    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
			    <div style="position: absolute; left: -5000px;"><input type="text" name="b_4d5ae11ec6fb973947670055f_e63c9ab02b" tabindex="-1" value=""></div>
			    <div class="clear"><input type="submit" value="Subscribe to Mailing List" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
			    </div>
			</form>
			</div>

			<!--End mc_embed_signup-->
			<nav class="navigation">
				<%= link_to "about", about_path %>
				<%= link_to "get involved", get_involved_path %>
				<%= link_to "jobs", jobs_path %>
				<%= link_to "faq", faq_path %>
				<%= link_to "code of conduct", code_of_conduct_path %>
				<%= link_to "supporters", supporters_path %>
				<%#= link_to "partners", root_path, class: "hide" %>
				<a target="_blank" href="http://girldevelopit.tumblr.com/">blog</a>
				<% if current_admin_user != nil %>
					<%= link_to "admin", admin_root_path %>
					<%= link_to "logout", destroy_admin_user_session_path %>
				<% end %>
			</nav>
			<nav class="navigation">
				<a target="_blank" href="https://twitter.com/girldevelopit" aria-label="GDI Twitter"><i class="fa fa-twitter"></i></a>
			  <a target="_blank" href="https://www.facebook.com/girldevelopit" aria-label="GDI Facebook"><i class="fa fa-facebook"></i></a>
			  <a target="_blank" href="http://girldevelopit.tumblr.com/" aria-label="GDI Tumblr"><i class="fa fa-tumblr"></i>
			</nav>

			<div class="footnote">
				<p>Girl Develop It, 1732 1st Ave #24681, New York, NY, 10128 USA</p>
				<p class="nonprofit-info">Girl Develop It is an exempt organization as described in Section 501(c)(3) of the Internal Revenue Code.</p>
				<p class="nonprofit-info">Our EIN is 46-3103695.</p>
			</div>

		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <%= link_to image_tag("gdi-logo.png"), root_path, class:"logo" %>
    <nav class="navigation">
      <ul>
        <li><%= link_to "donate", donate_path, class:active_page(donate_path) %></li>
        <li><%= link_to "about", about_path, class:active_page(about_path) %></li>
        <li><%= link_to "chapters", chapters_path, class:active_page(chapters_path) %></li>
        <li><%= link_to "materials", materials_path, class:active_page(materials_path)%></li>
        <li><%= link_to "supporters", supporters_path, class:active_page(supporters_path) %></li>
      </ul>
      <ul>
        <li>
          <a target="_blank" href="https://twitter.com/girldevelopit" aria-label="GDI Twitter">
            <i class="fa fa-twitter"></i>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://www.facebook.com/girldevelopit" aria-label="GDI Facebook">
            <i class="fa fa-facebook"></i>
          </a>
        </li>
        <li>
          <a target="_blank" href="http://girldevelopit.tumblr.com/" aria-label="GDI Tumblr">
            <i class="fa fa-tumblr"></i>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</header>